status = error
name = ElasticsearchPropertiesConfig

appender.console.type = Console
appender.console.name = rolling
appender.console.layout.type = ECSJsonLayout
appender.console.layout.dataset = elasticsearch.server

rootLogger.level = warn
rootLogger.appenderRef.console.ref = rolling

logger.entitlements_xpack_security.name = org.elasticsearch.entitlement.runtime.policy.PolicyManager.x-pack-security.org.elasticsearch.security
logger.entitlements_xpack_security.level = error

logger.entitlements_inference.name = org.elasticsearch.entitlement.runtime.policy.PolicyManager.x-pack-inference.software.amazon.awssdk.profiles
logger.entitlements_inference.level = error

logger.entitlements_ingest_attachment.name = org.elasticsearch.entitlement.runtime.policy.PolicyManager.ingest-attachment.ALL-UNNAMED
logger.entitlements_ingest_attachment.level = error

logger.entitlements_repository_gcs.name = org.elasticsearch.entitlement.runtime.policy.PolicyManager.repository-gcs.ALL-UNNAMED
logger.entitlements_repository_gcs.level = error

logger.entitlements_repository_s3.name = org.elasticsearch.entitlement.runtime.policy.PolicyManager.repository-s3.ALL-UNNAMED
logger.entitlements_repository_s3.level = error
