x-podman:
  in_pod: false

services:
  kibana:
    volumes:
      - type: bind
        source: ./kibana/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
        bind:
          selinux: z
      - type: bind
        source: ./kibana/node.options
        target: /usr/share/kibana/config/node.options
        read_only: true
        bind:
          selinux: z

  logstash:
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
        bind:
          selinux: z
      - type: bind
        source: ./logstash/config/log4j2.properties
        target: /usr/share/logstash/config/log4j2.properties
        read_only: true
        bind:
          selinux: z
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
        bind:
          selinux: z
      - type: bind
        source: ./logstash/patterns
        target: /usr/share/logstash/patterns
        read_only: true
        bind:
          selinux: z

  es01:
    volumes:
      - type: bind
        source: ./elasticsearch/config/log4j2.properties
        target: /usr/share/elasticsearch/config/log4j2.properties
        read_only: true
        bind:
          selinux: z

  es02:
    volumes:
      - type: bind
        source: ./elasticsearch/config/log4j2.properties
        target: /usr/share/elasticsearch/config/log4j2.properties
        read_only: true
        bind:
          selinux: z

  es03:
    volumes:
      - type: bind
        source: ./elasticsearch/config/log4j2.properties
        target: /usr/share/elasticsearch/config/log4j2.properties
        read_only: true
        bind:
          selinux: z

  filebeat:
    userns_mode: keep-id
    volumes:
      - type: bind
        source: ./filebeat/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
        read_only: true
        bind:
          selinux: z
      - type: bind
        source: ${XDG_RUNTIME_DIR}/podman/podman.sock
        target: /var/run/docker.sock
        read_only: true
        bind:
          selinux: z
      - type: bind
        source: ./logs
        target: /var/log
        read_only: true
        bind:
          selinux: z

  ilm-setup:
    volumes:
      - type: bind
        source: ./setup
        target: /setup
        read_only: true
        bind:
          selinux: z

  rules-import:
    volumes:
      - type: bind
        source: ./rules
        target: /rules
        read_only: true
        bind:
          selinux: z
